#!/usr/bin/env perl

package MAT::TestRun;
use base 'Apache::TestRun';
use Apache::TestConfig;

__PACKAGE__->new->run(@ARGV);

# See 'perldoc Apache::TestRun'
sub pre_configure
{
  my $self = shift;
  Apache::TestConfig::autoconfig_skip_module_add('mod_auth_tkt.c');
  $self->SUPER::pre_configure();
}

# Explicitly set servername, since we require .localdomain for our cookies
sub new_test_config {
      my $self = shift;
      $self->{conf_opts}->{servername} = 'localhost.localdomain';
      return $self->SUPER::new_test_config;
}

